# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("covr", "devtools"))
        shell: Rscript {0}

      - name: Get percent coverage
        run: |
          message('${{ github.workspace }}')
          x <- covr::package_coverage('${{ github.workspace }}', quiet=FALSE)
          p <- covr::percent_coverage(x)
          cat(p, file = "coverage.txt", sep = "")
        shell: Rscript {0}

      - name: Upload percent coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt

      - name: Generate percent coverage badge
        run: |
          cat coverage.txt
          COVERAGE=$(cat coverage.txt)
          curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-green.svg" > coverage.svg

      - name: Commit file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg # replace this with the path to your file
          git commit -m "Update badge" # replace this with your own commit message

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: coverage_badge
