# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages("covr")
        shell: Rscript {0}

      - name: Get percent coverage
        run: |
          message({{ github.workspace }})
          x <- covr::package_coverage(${{ github.workspace }})
          p <- covr::percent_coverage(x)
        shell: Rscript {0}

      - name: Save coverage data
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.json

      - name: Generate badge
        run: |
          cat coverage.json
          COVERAGE=$(cat coverage.json | jq '.["totals"]["percent"]')
          curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-green.svg" > coverage.svg

      - name: Save badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage.svg
