# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

    steps:
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          install.packages(c("covr", "devtools"))
        shell: Rscript {0}

      - name: Get percent coverage
        run: |
          message('${{ github.workspace }}')
          x <- covr::package_coverage('${{ github.workspace }}', quiet=FALSE)
          p <- covr::percent_coverage(x)
          cat(p, file = "coverage.txt", sep = "")
        shell: Rscript {0}

      - name: Upload percent coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt

      - name: Generate percent coverage badge
        run: |
          cat coverage.txt
          COVERAGE=$(cat coverage.txt)
          curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-green.svg" > coverage.svg

      - name: Upload coverage badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage.svg

      # - name: Commit changes
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add coverage.svg # replace this with the path to your file
      #     git commit -m "Update badge" # replace this with your own commit message

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.PAT_TOKEN }}
      #     branch: coverage_badge
      #     force: true

      # - uses: actions/checkout@v3
      #   with:
      #     ref: coverage_badge

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noteply.github.com"
          echo "see all files..."
          ls -la
          echo "performing git status..."
          git status
          echo "delete coverage_badge remote branch..."
          git push origin  :coverage_badge
          echo "delete other files except the badge..."
          ls | grep -xv "coverage.svg" | xargs rm -rf
          echo "staging badge..."
          git add coverage.svg
          echo "commit badge..."
          git commit -m "Update badge"
          echo "push remote..."
          git push --set-upstream origin coverage_badge

      # if [ -n "$(git status --porcelain)" ]; then
      #   echo "there are uncommitted changes"
      #   # if there are uncommitted changes, commit them
      #   git add coverage.svg
      #   git commit -m "Update badge"
      #   git push origin coverage_badge
      # fi

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.PAT_TOKEN }}
      #     branch: coverage_badge

      # - name: Push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   run: |
      #     git push -f origin coverage_badge
